spring:
  datasource:
    url: jdbc:h2:~/shift
    username:
    password:
  h2:
    console:
      enabled: true
      path: /h2-shift
  jpa:
    database: h2
    hibernate:
      ddl-auto: create
      show-sql: true
